# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Copyright (c) 2011-2020 ETH Zurich.

name: test

on:
  push: # run this workflow on every push
  # pull_request: # run this workflow on every pull_request

jobs:
  verify-router:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VerifiedSCION
        uses: actions/checkout@v2
      - name: Caching
        if: always()
        uses: gerbal/always-cache@v1.0.3
        with:
          # Needs to be a folder
          path: ${{ runner.workspace }}/.gobra
          key: vs-cache-router
      - name: Verify router package
        uses: jogasser/gobra-action@main
        with:
          caching: 1
          chop: 100
          viperBackend: VSWITHSILICON
          packages: router
          srcDirectory: gobra
      - name: Upload statistics report
        if: always() 
        uses: actions/upload-artifact@v2
        with:
          name: statistics-router
          path: ${{ runner.workspace }}/.gobra/stats.json     
      - name: Upload cache
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cache-router
          path: ${{ runner.workspace }}/.gobra/cache.json

   verify-conn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VerifiedSCION
        uses: actions/checkout@v2
      - name: Caching
        if: always()
        uses: gerbal/always-cache@v1.0.3
        with:
          # Needs to be a folder
          path: ${{ runner.workspace }}/.gobra
          key: vs-cache-conn
      - name: Verify conn package
        uses: jogasser/gobra-action@main
        with:
          caching: 1
          chop: 100
          viperBackend: VSWITHSILICON
          packages: conn
          srcDirectory: gobra
      - name: Upload statistics report
        if: always() 
        uses: actions/upload-artifact@v2
        with:
          name: statistics-conn
          path: ${{ runner.workspace }}/.gobra/stats.json     
      - name: Upload cache
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cache-conn
          path: ${{ runner.workspace }}/.gobra/cache.json
          
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout VerifiedSCION
        uses: actions/checkout@v2
      - name: Cache VerifiedSCION cache
        if: always()
        uses: gerbal/always-cache@v1.0.3
        with:
          # Needs to be a folder
          path: ${{ runner.workspace }}/.gobra
          key: vs-cache  
      - name: Verify packages
        uses: jogasser/gobra-action@main
        with:
          caching: 1
          viperBackend: VSWITHSILICON
          packageTimeout: 1h 
          excludePackages: "router conn"
          srcDirectory: gobra
      - name: Upload statistics report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: statistics
          path: ${{ runner.workspace }}/.gobra/stats.json     
      - name: Upload cache
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cache
          path: ${{ runner.workspace }}/.gobra/cache.json    
